/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userLogin;

/**
 *
 * @author Hirusha
 */



public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userIdTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        frogotLb = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        adminLb = new javax.swing.JLabel();
        backgroundLb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 93, 44));
        jLabel1.setText("ACCESS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 81, -1, -1));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("User ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 40));

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        userIdTxt.setBackground(new java.awt.Color(236, 236, 236));
        userIdTxt.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        userIdTxt.setToolTipText("");
        userIdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(userIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 289, 44));

        passwordTxt.setBackground(new java.awt.Color(236, 236, 236));
        passwordTxt.setFont(new java.awt.Font("Poppins", 0, 20)); // NOI18N
        passwordTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 326, 289, 44));

        frogotLb.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        frogotLb.setForeground(new java.awt.Color(34, 153, 233));
        frogotLb.setText("Forgot Password");
        jPanel1.add(frogotLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 388, 215, -1));

        loginBtn.setBackground(new java.awt.Color(249, 93, 44));
        loginBtn.setFont(new java.awt.Font("Poppins", 1, 19)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(null);
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 471, 104, 43));

        clearBtn.setBackground(new java.awt.Color(249, 93, 44));
        clearBtn.setFont(new java.awt.Font("Poppins", 1, 19)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(null);
        jPanel1.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 471, 104, 43));

        adminLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userLogin/admin.png"))); // NOI18N
        jPanel1.add(adminLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 80, 60));

        backgroundLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userLogin/loginimg.png"))); // NOI18N
        jPanel1.add(backgroundLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1084, 620));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLb;
    private javax.swing.JLabel backgroundLb;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel frogotLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField userIdTxt;
    // End of variables declaration//GEN-END:variables
}
