/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package content;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hirusha
 */
public class AssetPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssetPanel
     */
    public AssetPanel() {
        initComponents();
        
        jTable1Asset.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = jTable1Asset.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1Asset.getModel();

        txtRouteId.setText(model.getValueAt(selectedRow, 0).toString());
        txtType.setText(model.getValueAt(selectedRow, 1).toString());
        txtNo.setText(model.getValueAt(selectedRow, 2).toString());
    }
});
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1Asset = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtRouteId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1Asset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RouteID", "Type", "No"
            }
        ));
        jScrollPane3.setViewportView(jTable1Asset);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 720, 200));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 90, -1, 30));

        txtNo.setBackground(new java.awt.Color(236, 236, 236));
        txtNo.setFont(new java.awt.Font("Poppins", 0, 17)); // NOI18N
        txtNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, 32));

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, 50));

        txtType.setBackground(new java.awt.Color(236, 236, 236));
        txtType.setFont(new java.awt.Font("Poppins", 0, 17)); // NOI18N
        txtType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 150, 30));

        txtRouteId.setBackground(new java.awt.Color(236, 236, 236));
        txtRouteId.setFont(new java.awt.Font("Poppins", 0, 17)); // NOI18N
        txtRouteId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(txtRouteId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, 32));

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Route ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 30));

        jButton1.setBackground(new java.awt.Color(249, 93, 44));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 19)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VIEW SCHEDULE");
        jButton1.setActionCommand("");
        jButton1.setBorder(null);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 180, 40));

        btnAdd.setBackground(new java.awt.Color(249, 93, 44));
        btnAdd.setFont(new java.awt.Font("Poppins", 1, 19)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 70, 40));

        btnDel.setBackground(new java.awt.Color(249, 93, 44));
        btnDel.setFont(new java.awt.Font("Poppins", 1, 19)); // NOI18N
        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setText("DELETE");
        btnDel.setBorder(null);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 90, 40));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("SAVE");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ScheduleId", "No", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 400, 120));

        btnUpdate.setBackground(new java.awt.Color(249, 93, 44));
        btnUpdate.setFont(new java.awt.Font("Poppins", 1, 19)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(null);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 90, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        DefaultTableModel tbModel = (DefaultTableModel)jTable1Asset.getModel();
       
       if(jTable1Asset.getSelectedRowCount()==1){
           tbModel.removeRow(jTable1Asset.getSelectedRow());      
       }
       
       else{
           if(jTable1Asset.getSelectedRow()==0){
               JOptionPane.showMessageDialog(this, "The table is empty");
           } 
           else{
               JOptionPane.showMessageDialog(this, "Please select a single row to delete");
           }
       }
       
              txtRouteId.setText("");
               txtType.setText("");
               txtNo.setText("");
    }//GEN-LAST:event_btnDelActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(txtRouteId.getText().equals("")||txtType.getText().equals("")||txtNo.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Please enter all the details");
        }
        
        else{
               String data[] = {txtRouteId.getText(),txtType.getText(),txtNo.getText() };
               DefaultTableModel tbModel = (DefaultTableModel)jTable1Asset.getModel();
               
               tbModel.addRow(data);
               JOptionPane.showMessageDialog(this, "Data added successfully");
               
               txtRouteId.setText("");
               txtType.setText("");
               txtNo.setText("");
               
        }   
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = jTable1Asset.getSelectedRow();

        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to update.");
        return;
        }
    
        DefaultTableModel model = (DefaultTableModel) jTable1Asset.getModel();

        model.setValueAt(txtRouteId.getText(), selectedRow, 0);
        model.setValueAt(txtType.getText(), selectedRow, 1);
        model.setValueAt(txtNo.getText(), selectedRow, 2);

        JOptionPane.showMessageDialog(this, "Row updated successfully.");

        txtRouteId.setText("");
        txtType.setText("");
        txtNo.setText("");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
 
    }//GEN-LAST:event_btnUpdateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable1Asset;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtRouteId;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
